apiVersion: v1
kind: Namespace
metadata:
  name: bitirme_ns

--- 


apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitirme-deployment
  namespace: bitirme_ns
spec:
  selector:
    matchLabels:
      app: bitirme-app
  replicas: 3
  template:
    metadata:
      labels:
        app: bitirme-app 
    spec:
      containers:
      - name: bitime-container
        image: us-west1-docker.pkg.dev/bitirme-387623/bitirme/bitirme_img:22
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: 
  namespace: bitirme_ns
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: bitirme-app
  type: NodePort
---
