name: Second Workflow

on:
  repository_dispatch:
    types: [second-workflow]

jobs:
  modify-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Modify File
        run: |
          cat deployment.yaml
          sed -i 's+us-west1-docker.pkg.dev/bitirme-387623/bitirme/bitirme_img.*+us-west1-docker.pkg.dev/bitirme-387623/bitirme/bitirme_img:${{ github.event.client_payload.version }}+g' deployment.yaml
          cat deployment.yaml
          
      - name: Add changes
        run: |
          git config --global user.email "gurdalc19@itu.edu.tr"
          git config --global user.name "gurdalc19"
          git add .
      - name: Commit changes
        run: |
          git commit -m "Commit message"
          
      - name: Push 
        run: |
          git push https://github.com/gurdalc19/bitirme_manifast.git HEAD:main
